### ISSUE TITLE
What's an appropriate way to create this map?

### ISSUE THREAD

**Issue by maxjacobson** [maxjacobson/mapquest#1]
Thoughts:
- Leaflet
- some handmade d3.js thing (leaning toward this)

**Comment by dmanaster** [comment]
Check out https://github.com/kjordahl/geopandas

The guy who wrote it demoed it last week at Hack & Tell, and it was scary how good it is. 

I'm not sure how easy it would be to use though, or if the geo-spatial data for countries are easy to come by.

**Comment by maxjacobson** [comment]
Oh my god those are beautiful. They're like Miyazaki stills.

Not sure we can use it either, because the maps part needs to run in-browser interactively, so it must use JS I think...

**Comment by surrealdetective** [comment]
This one thread has resources for getting the geo-data for administrative boundaries, so if you wanted to zoom in and perhaps do counties surrounding your zip code, you maybe could?

http://gis.stackexchange.com/questions/23028/getting-polygons-of-all-countries-and-iso-3166-2-subdivisons

especially notable:
http://www.gadm.org/

**Comment by maxjacobson** [comment]
This looks beautiful to me: http://datamaps.github.io/

**Comment by maxjacobson** [comment]
whoa datamaps is almost too easy it feels like cheating. I'm going to sleep! :zzz:

**Comment by maxjacobson** [comment]
btw I'm not at all committed to datamaps but it is pretty promising. check out the datamaps branch to see a basic world map
